# Generated by DRE's release workflow (.github/scripts/package_managers.py); don't edit.
class Dre < Formula
  desc "Declarative Reporting Engine: SQL in, formatted files out"
  homepage "https://github.com/get-dre/dre"
  version "0.2.0"
  license "GPL-3.0-only"

  on_macos do
    on_arm do
      url "https://github.com/get-dre/dre/releases/download/v0.2.0/dre-0.2.0-macos-aarch64.tar.gz"
      sha256 "1eaa928a2ec1626a204178aae832fc95fb52e2a46c8963540ecb4382f3453f26"
    end
    on_intel do
      url "https://github.com/get-dre/dre/releases/download/v0.2.0/dre-0.2.0-macos-x86_64.tar.gz"
      sha256 "3bf29b07a4ae7684105eed8d50549f29a3f0286a15f692050f7f9f9554d63d74"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/get-dre/dre/releases/download/v0.2.0/dre-0.2.0-linux-aarch64.tar.gz"
      sha256 "42737379e22724e5d63b78aa84b0cffd07693b8aefab8d28af19b4b752af5de3"
    end
    on_intel do
      url "https://github.com/get-dre/dre/releases/download/v0.2.0/dre-0.2.0-linux-x86_64.tar.gz"
      sha256 "e588e61b42710d411dc56b67c9818fbe19dc864e29f16aee79bbc1f672420cf0"
    end
  end

  def install
    bin.install "dre"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/dre --version")
  end
end
