# Generated by DRE's release workflow (.github/scripts/package_managers.py); don't edit.
class Dre < Formula
  desc "Declarative Reporting Engine: SQL in, formatted files out"
  homepage "https://github.com/get-dre/dre"
  version "0.1.0"
  license "GPL-3.0-only"

  on_macos do
    on_arm do
      url "https://github.com/get-dre/dre/releases/download/v0.1.0/dre-0.1.0-macos-aarch64.tar.gz"
      sha256 "149b0a88d29fbc5d9ba1305f63e29c4fc4813ea214cf424d612577194277c097"
    end
    on_intel do
      url "https://github.com/get-dre/dre/releases/download/v0.1.0/dre-0.1.0-macos-x86_64.tar.gz"
      sha256 "efde04315789f5778eed002c031e0e6ba224b4fe65db8ceb62a1b67658d80d6b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/get-dre/dre/releases/download/v0.1.0/dre-0.1.0-linux-aarch64.tar.gz"
      sha256 "a8f4483cea6dda81de3385057f8abdbd094cfd792a076686d9dea9014d2095e6"
    end
    on_intel do
      url "https://github.com/get-dre/dre/releases/download/v0.1.0/dre-0.1.0-linux-x86_64.tar.gz"
      sha256 "722aa48693dee4a7bc294cc17a3d47c009ef6883a65aeaf54ccd52c4ae4e3ef6"
    end
  end

  def install
    bin.install "dre"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/dre --version")
  end
end
