# Generated by DRE's release workflow (.github/scripts/package_managers.py); don't edit.
class Dre < Formula
  desc "Declarative Reporting Engine: SQL in, formatted files out"
  homepage "https://github.com/get-dre/dre"
  version "0.2.1"
  license "GPL-3.0-only"

  on_macos do
    on_arm do
      url "https://github.com/get-dre/dre/releases/download/v0.2.1/dre-0.2.1-macos-aarch64.tar.gz"
      sha256 "172cb8ee18434bbe30eb8321bb97c377d13adc5ed8d2aaa947ddf9e1ac5a9ba5"
    end
    on_intel do
      url "https://github.com/get-dre/dre/releases/download/v0.2.1/dre-0.2.1-macos-x86_64.tar.gz"
      sha256 "eca4a5dd60a1beec8a4712edc84a2ff59f77db5650cceade49a91a0e305851f2"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/get-dre/dre/releases/download/v0.2.1/dre-0.2.1-linux-aarch64.tar.gz"
      sha256 "e97cd7eaaa6978b67054705891e320e9ff80816fa3e4949772a00afbe728f4de"
    end
    on_intel do
      url "https://github.com/get-dre/dre/releases/download/v0.2.1/dre-0.2.1-linux-x86_64.tar.gz"
      sha256 "964c6ee8bdd1ccd9528a73a251bbdbbbb1b3293a37f97ae0efc12764e533fc96"
    end
  end

  def install
    bin.install "dre"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/dre --version")
  end
end
